name: repository dispatch test

on:
  repository_dispatch:
    types: [hello]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: repository dispatch 1st step
      run: echo "${{ github.event.client_payload.branch }}"
    - name: repository dispatch 2nd step
      run: echo "${{ github.event.client_payload.stage }}"
