name: repository dispatch test

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [hello]

env:
  MY_VAR_STAGE: ${{ github.event.client_payload.stage || 'default_stage' }}
  MY_VAR_SECRET: ${{ secrets.MY_SECRET_ENV }}

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: echo client payload or default variable
      run: echo $MY_VAR_STAGE

    - name: echo test of my secret env
      run: echo $MY_VAR_SECRET