name: repository dispatch test

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [hello]

env:
  MY_VAR_STAGE: ${{ github.event.client_payload.stage || 'default_stage' }}

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: repository dispatch 1st step
      run: echo $MY_VAR_STAGE